name: JSON updater

on:
  schedule:
    - cron: '0,30 * * * *'
  workflow_dispatch:
  
jobs:
  fetch_and_upload:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download JSON
        run: |
          mkdir -p data
          curl -L ${{ vars.JSON_ENDPOINT }}?data=metacovid_weekly_ratio > data/metacovid_weekly_ratio.json
          curl -L ${{ vars.JSON_ENDPOINT }}?data=metacovid_weekly_incidence > data/metacovid_weekly_incidence.json
          curl -L ${{ vars.JSON_ENDPOINT }}?data=metacovid_osaka > data/metacovid_osaka.json
          curl -L ${{ vars.JSON_ENDPOINT }}?data=metacovid_tokyo > data/metacovid_tokyo.json
          curl -L ${{ vars.JSON_ENDPOINT }}?data=osaka > data/osaka.json
          curl -L ${{ vars.JSON_ENDPOINT }}?data=sendai > data/sendai.json
          curl -L ${{ vars.JSON_ENDPOINT }}?data=gifu > data/gifu.json
          curl -L ${{ vars.JSON_ENDPOINT }}?data=kawasaki > data/kawasaki.json
          curl -L ${{ vars.JSON_ENDPOINT }}?data=komatsu > data/komatsu.json
          curl -L ${{ vars.JSON_ENDPOINT }}?data=sapporo > data/sapporo.json
          curl -L ${{ vars.JSON_ENDPOINT }}?data=hospital_admission > data/hospital_admission.json
          curl -L ${{ vars.JSON_ENDPOINT }}?data=kyukyu > data/kyukyu.json
      - name: Diff files
        id: diff
        run: |
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true
      - name: Commit & Push
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m 'Update data'
          git push
        if: steps.diff.outcome == 'failure'
