name: JSON updater

on:
  schedule:
    - cron: '0,30 * * * *'
  workflow_dispatch:
  
jobs:
  fetch_and_upload:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download JSON
        run: |
          mkdir -p data
          curl -L ${{ vars.JSON_ENDPOINT }}?data=metacovid_weekly_ratio > data/metacovid_weekly_ratio.json
          curl -L ${{ vars.JSON_ENDPOINT }}?data=metacovid_weekly_incidence > data/metacovid_weekly_incidence.json
          curl -L ${{ vars.JSON_ENDPOINT }}?data=metacovid_osaka > data/metacovid_osaka.json
          curl -L ${{ vars.JSON_ENDPOINT }}?data=metacovid_tokyo > data/metacovid_tokyo.json
          curl -L ${{ vars.JSON_ENDPOINT }}?data=osaka > data/osaka.json
          curl -L ${{ vars.JSON_ENDPOINT }}?data=sendai > data/sendai.json
          curl -L ${{ vars.JSON_ENDPOINT }}?data=gifu > data/gifu.json
          curl -L ${{ vars.JSON_ENDPOINT }}?data=kawasaki > data/kawasaki.json
          curl -L ${{ vars.JSON_ENDPOINT }}?data=komatsu > data/komatsu.json
          curl -L ${{ vars.JSON_ENDPOINT }}?data=sapporo > data/sapporo.json
          curl -L ${{ vars.JSON_ENDPOINT }}?data=hospital_admission > data/hospital_admission.json
          curl -L ${{ vars.JSON_ENDPOINT }}?data=kyukyu > data/kyukyu.json
      - name: Validate JSON and Stage
        run: |
          for file in data/*.json; do
            if jq empty "$file"; then
              git add "$file"
            else
              echo "Invalid JSON: $file"
            fi
          done
      - name: Check for Changes
        id: changes
        run: |
          CHANGED=$(git diff --staged --name-only)
          if [ -z "$CHANGED" ]; then
            echo "No changes to commit."
            exit 78  # Neutral exit
          fi
      - name: Commit & Push
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git commit -m 'Update data'
          git push
